theme:
  name: material
  logo: _assets/aldin-logo.png
  favicon: _assets/aldin-favicon.png
  font:
    text: Poppins
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - header.autohide
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.tooltips
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: custom
      accent: custom

extra_css:
  - _assets/aldin-theme.css
