site_name: Aldin AI Custom Solutions
site_url: https://mokhayesh.github.io/aldin-accelerators
repo_url: https://github.com/mokhayesh/aldin-accelerators
repo_name: aldin-accelerators

theme:
  name: material
  logo: _assets/aldin-logo.png
  favicon: _assets/aldin-favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - header.autohide
    - content.code.copy
    - content.tooltips
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: custom
      accent: custom

extra_css:
  - _assets/aldin-theme.css

nav:
  - Home: index.md
  - Data Governance: data-governance/index.md
  - Prompt Engineering: prompt-engineering/index.md
  - Code Converter: code-converter/index.md
  - Data Genius: data-genius/index.md
  - MDM: mdm/index.md
  - Sidecar Apps: sidecar-applications/index.md
  - Synthetic Data Generator: synthetic-data-generator/index.md
  - Architecture: architecture/index.md
  - Test Data: test-data/index.md
  - Changelog: changelog.md
  - Contributing: contributing.md
